[
    {
        "marketing_design_id": 79,
        "buyer_name": "BUNGA",
        "code_order": "1234",
        "jumlah_design": 2,
        "order_number": "1234",
        "deadline": "2025-09-14T00:00:00.000Z",
        "jumlah_revisi": 4,
        "price_normal": "100",
        "price_discount": "0",
        "discount_percentage": "0",
        "required_files": "jpg, pdf",
        "file_and_chat": "https://example.com",
        "detail_project": "detail project",
        "create_at": null,
        "update_at": null,
        "card_id": null,
        "resolution": "hd",
        "input_by_id": 3,
        "input_by_name": "FAOZAN",
        "acc_by_id": 2,
        "acc_by_name": "AARON",
        "account_id": 3,
        "account_name": "ETERNAL",
        "offer_type_id": 1,
        "offer_type_name": "REPEAT ORDER",
        "project_type_id": 2,
        "project_type_name": "ORIGINAL",
        "style_id": 2,
        "style_name": "ANIME",
        "status_project_id": 1,
        "status_project_name": "ACCEPTED",
        "order_type_id": 1,
        "order_type_name": "REGULAR"
    }
]