[
    {
        "marketing_design_id": 79,
        "buyer_name": "BUNGA",
        "code_order": "1234",
        "jumlah_design": 2,
        "order_number": "1234",
        "deadline": "2025-09-14T00:00:00.000Z",
        "jumlah_revisi": 4,
        "price_normal": "100",
        "price_discount": "0",
        "discount_percentage": "0",
        "required_files": "jpg, pdf",
        "file_and_chat": "https://example.com",
        "detail_project": "detail project",
        "create_at": null,
        "update_at": null,
        "card_id": null,
        "resolution": "hd",
        "input_by_id": 3,
        "input_by_name": "FAOZAN",
        "acc_by_id": 2,
        "acc_by_name": "AARON",
        "account_id": 3,
        "account_name": "ETERNAL",
        "offer_type_id": 1,
        "offer_type_name": "REPEAT ORDER",
        "project_type_id": 2,
        "project_type_name": "ORIGINAL",
        "style_id": 2,
        "style_name": "ANIME",
        "status_project_id": 1,
        "status_project_name": "ACCEPTED",
        "order_type_id": 1,
        "order_type_name": "REGULAR"
    }
],


{
    "marketing_id": 46,
    "card_id": null,
    "buyer_name": "MANIA",
    "code_order": "1234",
    "order_number": "11122",
    "jumlah_track": 4,
    "duration": "UP TO 5 MIN",
    "jumlah_revisi": 3,
    "deadline": "2025-09-12T00:00:00.000Z",
    "price_normal": "140",
    "price_discount": "0.00",
    "discount": "5%",
    "basic_price": "0.00",
    "gig_link": "https://example.com",
    "reference_link": "https://example.com",
    "required_files": "https://example.com",
    "file_and_chat_link": "https://example.com",
    "detail_project": " ",
    "create_at": "2025-09-10T13:35:09.059Z",
    "update_at": "2025-09-12T21:52:39.996Z",
    "input_by": 4,
    "input_by_name": "APIL",
    "acc_by": 2,
    "acc_by_name": "GRACELLA",
    "account": 2,
    "account_name": "ALZHA",
    "order_type": 1,
    "order_type_name": "BASIC",
    "offer_type": 1,
    "offer_type_name": "REPEAT ORDER",
    "jenis_track": 1,
    "track_type_name": "TRACK 1",
    "genre": 2,
    "genre_name": "KIDS",
    "project_type": 1,
    "project_type_name": "ORIGINAL",
    "kupon_diskon_id": 3,
    "kupon_diskon_name": "PROMO NEW YEAR",
    "accept_status_id": 1,
    "accept_status_name": "Accepted"
}